databases:
    - name: chocolatlumiere-postgres
      databaseName: chocolatlumiere
      user: chocolatlumiere
      region: singapore
      plan: free
services:
    - type: web
      name: chocolatlumiere
      env: docker
      region: singapore
      plan: free
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: chocolatlumiere-postgres
                property: connectionString
          - key: REDIS_URL
            fromService:
                type: redis
                name: chocolatlumiere-redis
                property: connectionString
    - type: redis
      name: chocolatlumiere-redis
      ipAllowList:
          - source: 0.0.0.0/0
            description: everywhere
      plan: free
      maxmemoryPolicy: allkeys-lru
