databases:
    - name: shopify-chocolatlumiere
      databaseName: chocolatlumiere
      user: chocolatlumiere
      region: singapore

services:
    - type: web
      name: shopify-chocolatlumiere
      env: docker
      region: singapore
      plan: free
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: rails7_sample_staging
                property: connectionString
          - key: REDIS_URL
            fromService:
                type: redis
                name: shopify-chocolatlumiere
                property: connectionString
    - type: redis
      name: shopify-chocolatlumiere
      ipAllowList:
          - source: 0.0.0.0/0
            description: everywhere
      plan: free
      maxmemoryPolicy: allkeys-lru
