export const provinceCode = (provinceCode: string) => {
    switch (provinceCode) {
        case 'JP-01':
            return '北海道';
        case 'JP-02':
            return '青森県';
        case 'JP-03':
            return '岩手県';
        case 'JP-04':
            return '宮城県';
        case 'JP-05':
            return '秋田県';
        case 'JP-06':
            return '山形県';
        case 'JP-07':
            return '福島県';
        case 'JP-08':
            return '茨城県';
        case 'JP-09':
            return '栃木県';
        case 'JP-10':
            return '群馬県';
        case 'JP-11':
            return '埼玉県';
        case 'JP-12':
            return '千葉県';
        case 'JP-13':
            return '東京都';
        case 'JP-14':
            return '神奈川県';
        case 'JP-15':
            return '新潟県';
        case 'JP-16':
            return '富山県';
        case 'JP-17':
            return '石川県';
        case 'JP-18':
            return '福井県';
        case 'JP-19':
            return '山梨県';
        case 'JP-20':
            return '長野県';
        case 'JP-21':
            return '岐阜県';
        case 'JP-22':
            return '静岡県';
        case 'JP-23':
            return '愛知県';
        case 'JP-24':
            return '三重県';
        case 'JP-25':
            return '滋賀県';
        case 'JP-26':
            return '京都府';
        case 'JP-27':
            return '大阪府';
        case 'JP-28':
            return '兵庫県';
        case 'JP-29':
            return '奈良県';
        case 'JP-30':
            return '和歌山県';
        case 'JP-31':
            return '鳥取県';
        case 'JP-32':
            return '島根県';
        case 'JP-33':
            return '岡山県';
        case 'JP-34':
            return '広島県';
        case 'JP-35':
            return '山口県';
        case 'JP-36':
            return '徳島県';
        case 'JP-37':
            return '香川県';
        case 'JP-38':
            return '愛媛県';
        case 'JP-39':
            return '高知県';
        case 'JP-40':
            return '福岡県';
        case 'JP-41':
            return '佐賀県';
        case 'JP-42':
            return '長崎県';
        case 'JP-43':
            return '熊本県';
        case 'KP-44':
            return '大分県';
        case 'JP-45':
            return '宮崎県';
        case 'JP-46':
            return '鹿児島県';
        case 'JP-47':
            return '沖縄県';
        default:
            return '';
    }
};
